
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    url: jdbc:mysql://116.63.173.57:33061/monitor_sys?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://192.168.3.171:3306/monitor_sys?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: develop
    password: Aman@2020
    driver-class-name: com.mysql.cj.jdbc.Driver
#  kafka:
#    consumer:
#      bootstrap-servers:
#        - 192.168.3.237:9092
#      group-id: test-alarm
#      enable-auto-commit: true
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      auto-offset-reset: earliest


logging:
  level:
    com.zhikuntech.intellimonitor.windpowerforecast.domain.service: debug
    com.zhikuntech.intellimonitor.windpowerforecast.domain.mapper: debug

