
spring:
  datasource:
    url: jdbc:mysql://192.168.3.171:3306/monitor_sys?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: develop
    password: Aman@2020
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 7
    host: 192.168.3.179
    port: 6379
  kafka:
    bootstrap-servers: 192.168.3.237:9092
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-hello-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhikuntech.intellimonitor.messagepush.domain.pojo.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#logging:
#  level:
#    com.zhikuntech.intellimonitor.messagepush.domain.mapper: debug



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

golden:
  ip: 1.117.33.103
  port: 6327
  user: sa
  password: golden
  poolSize: 25
  maxSize: 50

websocket.config: true


