

eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.174:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

